/**
 * One-off script to populate Firestore with the original mock data.
 * Run once against a fresh Firestore database: npx tsx scripts/seed-firestore.ts
 */
import { getDb } from "../src/lib/firebase-admin";
import type { Activity } from "../src/features/activities/types";
import type { EventInfo } from "../src/features/event/types";

const activities: Activity[] = [
  {
    id: "running",
    name: "Running",
    category: "segmented",
    description:
      "Lari santai menyusuri pantai untuk memulai hari dengan energi positif.",
    icon: "🚶",
    location: "Area Pantai Utama",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: 12,
    quotaTaken: 0,
    tags: ["outdoor", "cardio"],
    coach: "Kensrie",
    president: null,
  },
  {
    id: "wwf",
    name: "WWF",
    category: "segmented",
    description:
      "Sesi latihan fungsional intensitas tinggi untuk membangun stamina dan kekuatan.",
    icon: "🥊",
    location: "Beach Deck A",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: 10,
    quotaTaken: 0,
    tags: ["indoor-outdoor", "strength"],
    coach: "Irvani",
    president: null,
  },
  {
    id: "aqua-yoga",
    name: "Aqua Yoga",
    category: "segmented",
    description: "Yoga menenangkan di air untuk relaksasi tubuh dan pikiran.",
    icon: "🏊",
    location: "Kolam Renang",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: 12,
    quotaTaken: 0,
    tags: ["water", "relax"],
    president: null,
  },
  {
    id: "pilates",
    name: "Pilates",
    category: "segmented",
    description:
      "Sesi pilates untuk membentuk kekuatan inti dan fleksibilitas tubuh.",
    icon: "🧘‍♀️",
    location: "Studio Indoor",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: 10,
    quotaTaken: 0,
    tags: ["indoor", "core"],
    coach: "Okki",
    president: null,
  },
  {
    id: "zumba",
    name: "Zumba",
    category: "segmented",
    description: "Sesi zumba energik diiringi musik summer yang ceria.",
    icon: "🎵",
    location: "Beach Deck B",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: 12,
    quotaTaken: 0,
    tags: ["dance", "cardio"],
    coach: "Dewi",
    president: null,
  },
  {
    id: "swimming",
    name: "Swimming",
    category: "open",
    description: "Berenang bebas di kolam renang sepanjang sesi wellbeing.",
    icon: "🏊",
    location: "Kolam Renang",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: null,
    quotaTaken: 0,
    tags: ["water"],
  },
  {
    id: "badminton",
    name: "Badminton",
    category: "open",
    description: "Main badminton santai bersama rekan kerja.",
    icon: "🏸",
    location: "Lapangan Indoor",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: null,
    quotaTaken: 0,
    tags: ["indoor"],
  },
  {
    id: "volleyball",
    name: "Volleyball",
    category: "open",
    description: "Voli pantai seru bersama tim untuk mencairkan suasana.",
    icon: "🏐",
    location: "Lapangan Pantai",
    day: 2,
    timeWindow: "Fit Rave · 07.30 - 10.00",
    quota: null,
    quotaTaken: 0,
    tags: ["outdoor", "team"],
  },
];

const eventInfo: EventInfo = {
  scheduleVisible: true,
  day1: {
    title: "Menyamakan Vibrasi — Ruwatan Wayang",
    description:
      "Prosesi ruwatan bersama dalang untuk membuka rangkaian Fit Rave dengan penuh makna.",
    date: "2026-07-16",
    time: "Sepanjang hari",
    dresscode: {
      items: ["Atasan Putih", "Bawahan Kain"],
      note:
        "Laki-laki: Ikat Kepala. Perempuan: diusahakan rambut diikat ala Jawa.",
    },
    agenda: [
      {
        id: "persiapan",
        title: "Persiapan",
        timeStart: "14:00",
        timeEnd: "16:00",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "pamedaring-1",
        title: "Pamedaring Ruwat oleh Ki Supriyadi",
        timeStart: "16:00",
        timeEnd: "16:30",
        venue: "Limasan",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "pamedaring-2",
        title: "Pamedaring Ruwat oleh Eko Hand",
        timeStart: "16:30",
        timeEnd: "16:45",
        venue: "Limasan",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "upacara-ruwat",
        title: "Upacara Ritual Ruwat",
        timeStart: "16:45",
        timeEnd: "17:45",
        venue: "Limasan",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "pemercikan-air",
        title: "Pemercikan Air Ruwat",
        timeStart: "17:45",
        timeEnd: "18:45",
        venue: "Limasan",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "penyeberangan-arwah",
        title: "Upacara Ritual Penyeberangan Arwah & Karahayon",
        timeStart: "18:45",
        timeEnd: "19:00",
        venue: "Limasan",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "warnasari",
        title: "Warnasari & Ngobrol Santai",
        timeStart: "19:00",
        timeEnd: "Selesai",
        venue: "Limasan",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
    ],
  },
  day2: {
    title: "Wellbeing Day",
    description:
      "Rangkaian aktivitas seru sepanjang hari, dari olahraga pagi sampai makan malam bersama.",
    date: "2026-07-17",
    agenda: [
      {
        id: "gather-office",
        title: "Kumpul di Kantor",
        timeStart: "06:30",
        timeEnd: "07:00",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "opening-mc",
        title: "Opening MC & Shot Brief",
        timeStart: "07:00",
        timeEnd: "07:20",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "travel-to-aria",
        title: "Perjalanan dari Kantor ke Aria",
        timeStart: "07:20",
        timeEnd: "07:25",
        venue: "On The Road",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "snooze",
        title: "Snooze",
        timeStart: "07:25",
        timeEnd: "07:55",
        venue: "Aria Swimming Pool",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "fit-rave",
        title: "Fit Rave",
        timeStart: "07:55",
        timeEnd: "09:55",
        venue: "Aria Swimming Pool",
        status: "confirmed",
        description:
          "Sesi olahraga & wellbeing — seluruh aktivitas segmented dan open activity berlangsung di sesi ini.",
        dresscode: { items: ["Beachwear Outfit"], note: "" },
      },
      {
        id: "refresh-cooldown",
        title: "Refresh, Cool Down & Ganti Baju",
        timeStart: "09:55",
        timeEnd: "10:55",
        venue: "Aria Swimming Pool / Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "travel-back-office",
        title: "Perjalanan kembali ke Kantor Werkudara",
        timeStart: "10:55",
        timeEnd: "11:00",
        venue: "On The Road",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "sound-healing",
        title: "Sound Healing",
        timeStart: "11:00",
        timeEnd: "11:45",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "jumat-lunch",
        title: "Shalat Jum'at & Lunch",
        timeStart: "11:45",
        timeEnd: "13:15",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "general-briefing",
        title: "General Briefing & Opening Speech",
        timeStart: "13:15",
        timeEnd: "13:45",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "development-1",
        title: "Development Session - 1",
        timeStart: "13:45",
        timeEnd: "15:15",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "coffee-break",
        title: "Coffee Break",
        timeStart: "15:15",
        timeEnd: "15:45",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "development-2",
        title: "Development Session - 2",
        timeStart: "15:45",
        timeEnd: "17:15",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "closing-speech",
        title: "Closing Speech",
        timeStart: "17:15",
        timeEnd: "17:45",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "gala-prep",
        title: "Persiapan Gala Dinner",
        timeStart: "17:45",
        timeEnd: "18:45",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "travel-gala",
        title: "Perjalanan ke Gala Dinner",
        timeStart: "18:45",
        timeEnd: "19:10",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "gala-dinner",
        title: "Gala Dinner",
        timeStart: "19:10",
        timeEnd: "22:10",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
      {
        id: "travel-back-final",
        title: "Perjalanan kembali ke Kantor Werkudara",
        timeStart: "22:10",
        timeEnd: "22:35",
        venue: "Werkudara Office",
        status: "confirmed",
        description: "",
        dresscode: { items: [], note: "" },
      },
    ],
  },
};

async function seed() {
  const db = getDb();
  const activityWrites = activities.map((activity) =>
    db.collection("activities").doc(activity.id).set(activity),
  );
  await Promise.all(activityWrites);
  console.log(`Seeded ${activities.length} activities.`);

  await db.collection("event").doc("info").set(eventInfo);
  console.log("Seeded event/info.");
}

seed()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });
